# -*- coding: utf-8 -*-
"""Package_building_and _OOP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qQdpA-_6O_QNAoQoYxTX8cDrcxHXQW7r

# Package Building and Object-Oriented Programming
"""

class CalculatorInterface:
    def calculate(self, operation: str, a: float, b: float) -> float:
        """Abstract method that must be implemented by any child class."""
        pass

"""## 2. INHERITANCE

### BasicCalculator "inherits" the structure from CalculatorInterface.
"""

class BasicCalculator(CalculatorInterface):

    def __init__(self):
        # 3. ENCAPSULATION
        # We use a double underscore (__) to make this variable private.
        # It cannot be accessed or modified directly from outside the class.
        self.__latest_result = 0.0

"""## 3. ENCAPSULATION
### We use a double underscore (__) to make this variable private.
### It cannot be accessed or modified directly from outside the class.
"""

class BasicCalculator(CalculatorInterface):

    def __init__(self):
        self.__latest_result = 0.0

    # Getter method to safely access the private variable
    def get_latest_result(self):
        return self.__latest_result

    # Setter method to safely update the private variable internally
    def _update_result(self, value):
        self.__latest_result = value

    # Implementing the abstract method
    def calculate(self, operation: str, a: float, b: float) -> float:
        if operation == "add":
            self._update_result(a + b)
        elif operation == "subtract":
            self._update_result(a - b)
        else:
            raise ValueError(f"Operation '{operation}' not supported by BasicCalculator.")

        return self.get_latest_result()

""" ## 4. Polymorphism
 ### Overriding the calculate method
"""

class AdvancedCalculator(BasicCalculator):


    def calculate(self, operation: str, a: float, b: float) -> float:
        if operation == "power":
            self._update_result(a ** b)
            return self.get_latest_result()

        # If it's not 'power', hand it off to the parent class (BasicCalculator)
        return super().calculate(operation, a, b)

"""### Testing the New cretaed calculator tool we made"""

# Let's test our OOP Calculator
if __name__ == "__main__":
    # Create instances
    basic_calc = BasicCalculator()
    advanced_calc = AdvancedCalculator()

    print("--- Testing Basic Calculator ---")
    basic_calc.calculate("add", 10, 5)
    basic_calc.calculate("subtract", 10, 5)
    # The basic calculator doesn't know how to do exponents:
    #basic_calc.calculate("power", 2, 3)

    print("\n--- Testing Advanced Calculator ---")
    # The advanced calculator can do basic operations AND power operations
    advanced_calc.calculate("add", 10, 5)
    advanced_calc.calculate("power", 2, 3)

    print("\n--- Testing Encapsulation ---")
    # Trying to read or change the private variable directly will fail or create a dummy variable
    # print(basic_calc.__latest_result) # <-- Uncommenting this line will crash the program with an AttributeError!
    print(f"Safely accessed via getter: {basic_calc.get_latest_result()}")

basic_calc.calculate("add", 10, 5)

